### ISSUE TITLE
RCTLivePlayer" was not found in the UIManager

### ISSUE THREAD

**Issue by StevenB45** [wonday/react-native-live-stream#1]
Hello,

I just want to play an rtsp feed, so I installed your plugin with :  `npm i react-native-live-stream` and `react-native link react-native-live-stream`. Only for Android at the moment.

But I have a problem: 
`Invariant Violation: Invariant Violation: requireNativeComponent: `
`RCTLivePlayer" was not found in the UIManager.`

`This error is located at:`
   ` in RCTLivePlayer (at LivePlayer.js:59)`
    `in LivePlayer (at CameraView.js:405)`
`...`

Do you have any idea ? 

Thank you so much.

**Comment by StevenB45** [comment]
I found my mistake! I needed to manually link  MainApplication.java. But now i have a blank screen when i launch the player.

**Comment by wonday** [comment]
It does not contain controls, it just a player view.
If you can not see video, please change source and try again.

**Comment by kolawoletech** [comment]
Same issue here, source is fine

**Comment by dstrtop1** [comment]
@StevenB45 Good day!
can you please explain how did you manually link MainApplication.java ?

**Comment by vipzz** [comment]
Im facing this problem on IOS

**Comment by Peis7** [comment]
facing same problem on IOS

**Comment by yusufozcan** [comment]
I tried many alternatives for rtmp stream viewing. All libraries producing an error like `RCT..... was not found`. 

For me, the problem was with flutter. I don't know what exactly flutter is. I guess it is a debugger extension. Anyway, in podfile there is some codes like below.


**podfile**
```
...
# Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
add_flipper_pods!
post_install do |installer|
       flipper_post_install(installer)
end
```

But this kind of libraries inserting or wants you to insert `use_frameworks!` line to your pod file. In the commented section of above code, it says if you have `use_frameworks!` line, disable flutter installation. Then I decided to remove everything related with flutter. From podfile and AppDelegate.m file. Then finally I was able to solve my problem.

**Comment by nguyentuanit97** [comment]
Im facing this problem on IOS

**Comment by guybit7** [comment]
???
